service: google-vision
# frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: us-east-1
  # memorySize: 256
  # timeout: 120
  iam:
    role: arn:aws:iam::073464789998:role/AwsServiceCustomRolForLambdaExecution

functions:
  api:
    handler: index.handler
    # ephemeralStorageSize: 1024
    # environment: ${file(env.${opt:stage, self:provider.stage}.json)}
    # url: true
    # events:
    #   - httpApi:
    #       method: POST
    #       path: /vision
    layers:
      - arn:aws:lambda:us-east-1:073464789998:layer:google-vision-layer:1
package:
  exclude:
    - .vscode
    - layers/**
    - "node_modules/**"
    - .gitignore
    - "env.dev.json"
    - "env.prod.json"

plugins:
  - serverless-offline